[package]
name = "simulate_mm"
version = "0.1.0"
authors = ["Edoardo Morandi <emorandi@rnaframework.com>"]
edition = "2018"

[dependencies]
clap = { version = "4.5.18", features = ["derive"] }
rand = "0.8.5"
bstr = "1.10.0"
bincode = "1.1.3"
itertools = "0.13.0"
