[package]
name = "simulate_mm"
version = "0.1.0"
authors = ["Edoardo Morandi <emorandi@rnaframework.com>"]
edition = "2018"

[dependencies]
structopt = "0.3.20"
rand = "0.8.5"
bstr = "0.1.2"
bincode = "1.1.3"
itertools = "0.8.0"
